/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tek_vlc_jni_Vlc */

#ifndef _Included_com_tek_vlc_jni_Vlc
#define _Included_com_tek_vlc_jni_Vlc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tek_vlc_jni_Vlc
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tek_vlc_jni_Vlc_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
