package com.tek.vlc.jna;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libvlc_subtitle_track_t extends Structure {
    /** C type : char* */
    public Pointer psz_encoding;
    public libvlc_subtitle_track_t() {
        super();
    }
    protected List<? > getFieldOrder() {
        return Arrays.asList("psz_encoding");
    }
    /** @param psz_encoding C type : char* */
    public libvlc_subtitle_track_t(Pointer psz_encoding) {
        super();
        this.psz_encoding = psz_encoding;
    }
    public static class ByReference extends libvlc_subtitle_track_t implements Structure.ByReference {
        
    };
    public static class ByValue extends libvlc_subtitle_track_t implements Structure.ByValue {
        
    };
}
