package com.tek.vlc.jna;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libvlc_media_stats_t extends Structure {
    public int i_read_bytes;
    public float f_input_bitrate;
    public int i_demux_read_bytes;
    public float f_demux_bitrate;
    public int i_demux_corrupted;
    public int i_demux_discontinuity;
    public int i_decoded_video;
    public int i_decoded_audio;
    public int i_displayed_pictures;
    public int i_lost_pictures;
    public int i_played_abuffers;
    public int i_lost_abuffers;
    public int i_sent_packets;
    public int i_sent_bytes;
    public float f_send_bitrate;
    public libvlc_media_stats_t() {
        super();
    }
    protected List<? > getFieldOrder() {
        return Arrays.asList("i_read_bytes", "f_input_bitrate", "i_demux_read_bytes", "f_demux_bitrate", "i_demux_corrupted", "i_demux_discontinuity", "i_decoded_video", "i_decoded_audio", "i_displayed_pictures", "i_lost_pictures", "i_played_abuffers", "i_lost_abuffers", "i_sent_packets", "i_sent_bytes", "f_send_bitrate");
    }
    public libvlc_media_stats_t(Pointer peer) {
        super(peer);
    }
    public static class ByReference extends libvlc_media_stats_t implements Structure.ByReference {
        
    };
    public static class ByValue extends libvlc_media_stats_t implements Structure.ByValue {
        
    };
}

