package com.tek.vlc.jna;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libvlc_rectangle_t extends Structure {
    public int top;
    public int left;
    public int bottom;
    public int right;
    public libvlc_rectangle_t() {
        super();
    }
    protected List<? > getFieldOrder() {
        return Arrays.asList("top", "left", "bottom", "right");
    }
    public libvlc_rectangle_t(int top, int left, int bottom, int right) {
        super();
        this.top = top;
        this.left = left;
        this.bottom = bottom;
        this.right = right;
    }
    public libvlc_rectangle_t(Pointer peer) {
        super(peer);
    }
    public static class ByReference extends libvlc_rectangle_t implements Structure.ByReference {
        
    };
    public static class ByValue extends libvlc_rectangle_t implements Structure.ByValue {
        
    };
}

