package com.tek.vlc.jna;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libvlc_log_message_t extends Structure {
    /** 0=INFO, 1=ERR, 2=WARN, 3=DBG */
    public int i_severity;
    /**
     * module type<br>
     * C type : const char*
     */
    public Pointer psz_type;
    /**
     * module name<br>
     * C type : const char*
     */
    public Pointer psz_name;
    /**
     * optional header<br>
     * C type : const char*
     */
    public Pointer psz_header;
    /**
     * message<br>
     * C type : const char*
     */
    public Pointer psz_message;
    public libvlc_log_message_t() {
        super();
    }
    protected List<? > getFieldOrder() {
        return Arrays.asList("i_severity", "psz_type", "psz_name", "psz_header", "psz_message");
    }
    /**
     * @param i_severity 0=INFO, 1=ERR, 2=WARN, 3=DBG<br>
     * @param psz_type module type<br>
     * C type : const char*<br>
     * @param psz_name module name<br>
     * C type : const char*<br>
     * @param psz_header optional header<br>
     * C type : const char*<br>
     * @param psz_message message<br>
     * C type : const char*
     */
    public libvlc_log_message_t(int i_severity, Pointer psz_type, Pointer psz_name, Pointer psz_header, Pointer psz_message) {
        super();
        this.i_severity = i_severity;
        this.psz_type = psz_type;
        this.psz_name = psz_name;
        this.psz_header = psz_header;
        this.psz_message = psz_message;
    }
    public libvlc_log_message_t(Pointer peer) {
        super(peer);
    }
    public static class ByReference extends libvlc_log_message_t implements Structure.ByReference {
        
    };
    public static class ByValue extends libvlc_log_message_t implements Structure.ByValue {
        
    };
}

