package com.tek.vlc.bridj;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libvlc") 
public class libvlc_media_stats_t extends StructObject {
    static {
        BridJ.register();
    }
    @Field(0) 
    public int i_read_bytes() {
        return this.io.getIntField(this, 0);
    }
    @Field(0) 
    public libvlc_media_stats_t i_read_bytes(int i_read_bytes) {
        this.io.setIntField(this, 0, i_read_bytes);
        return this;
    }
    @Field(1) 
    public float f_input_bitrate() {
        return this.io.getFloatField(this, 1);
    }
    @Field(1) 
    public libvlc_media_stats_t f_input_bitrate(float f_input_bitrate) {
        this.io.setFloatField(this, 1, f_input_bitrate);
        return this;
    }
    @Field(2) 
    public int i_demux_read_bytes() {
        return this.io.getIntField(this, 2);
    }
    @Field(2) 
    public libvlc_media_stats_t i_demux_read_bytes(int i_demux_read_bytes) {
        this.io.setIntField(this, 2, i_demux_read_bytes);
        return this;
    }
    @Field(3) 
    public float f_demux_bitrate() {
        return this.io.getFloatField(this, 3);
    }
    @Field(3) 
    public libvlc_media_stats_t f_demux_bitrate(float f_demux_bitrate) {
        this.io.setFloatField(this, 3, f_demux_bitrate);
        return this;
    }
    @Field(4) 
    public int i_demux_corrupted() {
        return this.io.getIntField(this, 4);
    }
    @Field(4) 
    public libvlc_media_stats_t i_demux_corrupted(int i_demux_corrupted) {
        this.io.setIntField(this, 4, i_demux_corrupted);
        return this;
    }
    @Field(5) 
    public int i_demux_discontinuity() {
        return this.io.getIntField(this, 5);
    }
    @Field(5) 
    public libvlc_media_stats_t i_demux_discontinuity(int i_demux_discontinuity) {
        this.io.setIntField(this, 5, i_demux_discontinuity);
        return this;
    }
    @Field(6) 
    public int i_decoded_video() {
        return this.io.getIntField(this, 6);
    }
    @Field(6) 
    public libvlc_media_stats_t i_decoded_video(int i_decoded_video) {
        this.io.setIntField(this, 6, i_decoded_video);
        return this;
    }
    @Field(7) 
    public int i_decoded_audio() {
        return this.io.getIntField(this, 7);
    }
    @Field(7) 
    public libvlc_media_stats_t i_decoded_audio(int i_decoded_audio) {
        this.io.setIntField(this, 7, i_decoded_audio);
        return this;
    }
    @Field(8) 
    public int i_displayed_pictures() {
        return this.io.getIntField(this, 8);
    }
    @Field(8) 
    public libvlc_media_stats_t i_displayed_pictures(int i_displayed_pictures) {
        this.io.setIntField(this, 8, i_displayed_pictures);
        return this;
    }
    @Field(9) 
    public int i_lost_pictures() {
        return this.io.getIntField(this, 9);
    }
    @Field(9) 
    public libvlc_media_stats_t i_lost_pictures(int i_lost_pictures) {
        this.io.setIntField(this, 9, i_lost_pictures);
        return this;
    }
    @Field(10) 
    public int i_played_abuffers() {
        return this.io.getIntField(this, 10);
    }
    @Field(10) 
    public libvlc_media_stats_t i_played_abuffers(int i_played_abuffers) {
        this.io.setIntField(this, 10, i_played_abuffers);
        return this;
    }
    @Field(11) 
    public int i_lost_abuffers() {
        return this.io.getIntField(this, 11);
    }
    @Field(11) 
    public libvlc_media_stats_t i_lost_abuffers(int i_lost_abuffers) {
        this.io.setIntField(this, 11, i_lost_abuffers);
        return this;
    }
    @Field(12) 
    public int i_sent_packets() {
        return this.io.getIntField(this, 12);
    }
    @Field(12) 
    public libvlc_media_stats_t i_sent_packets(int i_sent_packets) {
        this.io.setIntField(this, 12, i_sent_packets);
        return this;
    }
    @Field(13) 
    public int i_sent_bytes() {
        return this.io.getIntField(this, 13);
    }
    @Field(13) 
    public libvlc_media_stats_t i_sent_bytes(int i_sent_bytes) {
        this.io.setIntField(this, 13, i_sent_bytes);
        return this;
    }
    @Field(14) 
    public float f_send_bitrate() {
        return this.io.getFloatField(this, 14);
    }
    @Field(14) 
    public libvlc_media_stats_t f_send_bitrate(float f_send_bitrate) {
        this.io.setFloatField(this, 14, f_send_bitrate);
        return this;
    }
    public libvlc_media_stats_t() {
        super();
    }
    public libvlc_media_stats_t(Pointer pointer) {
        super(pointer);
    }
}

