package com.tek.vlc.bridj;

import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;

import com.tek.vlc.bridj.LibvlcLibrary.libvlc_track_type_t;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libvlc") 
public class libvlc_media_track_info_t extends StructObject {
    static {
        BridJ.register();
    }
    @Field(0) 
    public int i_codec() {
        return this.io.getIntField(this, 0);
    }
    @Field(0) 
    public libvlc_media_track_info_t i_codec(int i_codec) {
        this.io.setIntField(this, 0, i_codec);
        return this;
    }
    @Field(1) 
    public int i_id() {
        return this.io.getIntField(this, 1);
    }
    @Field(1) 
    public libvlc_media_track_info_t i_id(int i_id) {
        this.io.setIntField(this, 1, i_id);
        return this;
    }
    /** C type : libvlc_track_type_t */
    @Field(2) 
    public IntValuedEnum<libvlc_track_type_t > i_type() {
        return this.io.getEnumField(this, 2);
    }
    /** C type : libvlc_track_type_t */
    @Field(2) 
    public libvlc_media_track_info_t i_type(IntValuedEnum<libvlc_track_type_t > i_type) {
        this.io.setEnumField(this, 2, i_type);
        return this;
    }
    @Field(3) 
    public int i_profile() {
        return this.io.getIntField(this, 3);
    }
    @Field(3) 
    public libvlc_media_track_info_t i_profile(int i_profile) {
        this.io.setIntField(this, 3, i_profile);
        return this;
    }
    @Field(4) 
    public int i_level() {
        return this.io.getIntField(this, 4);
    }
    @Field(4) 
    public libvlc_media_track_info_t i_level(int i_level) {
        this.io.setIntField(this, 4, i_level);
        return this;
    }
    /** C type : u_union */
    @Field(5) 
    public libvlc_media_track_info_t.u_union u() {
        return this.io.getNativeObjectField(this, 5);
    }
    /** C type : u_union */
    @Field(5) 
    public libvlc_media_track_info_t u(libvlc_media_track_info_t.u_union u) {
        this.io.setNativeObjectField(this, 5, u);
        return this;
    }
    /** <i>native declaration : line 868</i> */
    @Union 
    public static class u_union extends StructObject {
        static {
            BridJ.register();
        }
        /** C type : audio_struct */
        @Field(0) 
        public libvlc_media_track_info_t.u_union.audio_struct audio() {
            return this.io.getNativeObjectField(this, 0);
        }
        /** C type : audio_struct */
        @Field(0) 
        public u_union audio(libvlc_media_track_info_t.u_union.audio_struct audio) {
            this.io.setNativeObjectField(this, 0, audio);
            return this;
        }
        /** C type : video_struct */
        @Field(1) 
        public libvlc_media_track_info_t.u_union.video_struct video() {
            return this.io.getNativeObjectField(this, 1);
        }
        /** C type : video_struct */
        @Field(1) 
        public u_union video(libvlc_media_track_info_t.u_union.video_struct video) {
            this.io.setNativeObjectField(this, 1, video);
            return this;
        }
        /** <i>native declaration : line 869</i> */
        public static class audio_struct extends StructObject {
            static {
                BridJ.register();
            }
            @Field(0) 
            public int i_channels() {
                return this.io.getIntField(this, 0);
            }
            @Field(0) 
            public audio_struct i_channels(int i_channels) {
                this.io.setIntField(this, 0, i_channels);
                return this;
            }
            @Field(1) 
            public int i_rate() {
                return this.io.getIntField(this, 1);
            }
            @Field(1) 
            public audio_struct i_rate(int i_rate) {
                this.io.setIntField(this, 1, i_rate);
                return this;
            }
            public audio_struct() {
                super();
            }
            public audio_struct(Pointer pointer) {
                super(pointer);
            }
        };
        /** <i>native declaration : line 874</i> */
        public static class video_struct extends StructObject {
            static {
                BridJ.register();
            }
            @Field(0) 
            public int i_height() {
                return this.io.getIntField(this, 0);
            }
            @Field(0) 
            public video_struct i_height(int i_height) {
                this.io.setIntField(this, 0, i_height);
                return this;
            }
            @Field(1) 
            public int i_width() {
                return this.io.getIntField(this, 1);
            }
            @Field(1) 
            public video_struct i_width(int i_width) {
                this.io.setIntField(this, 1, i_width);
                return this;
            }
            public video_struct() {
                super();
            }
            public video_struct(Pointer pointer) {
                super(pointer);
            }
        };
        public u_union() {
            super();
        }
        public u_union(Pointer pointer) {
            super(pointer);
        }
    };
    public libvlc_media_track_info_t() {
        super();
    }
    public libvlc_media_track_info_t(Pointer pointer) {
        super(pointer);
    }
}

