package com.tek.vlc.bridj;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libvlc") 
public class libvlc_track_description_t extends StructObject {
    static {
        BridJ.register();
    }
    @Field(0) 
    public int i_id() {
        return this.io.getIntField(this, 0);
    }
    @Field(0) 
    public libvlc_track_description_t i_id(int i_id) {
        this.io.setIntField(this, 0, i_id);
        return this;
    }
    /** C type : char* */
    @Field(1) 
    public Pointer<Byte > psz_name() {
        return this.io.getPointerField(this, 1);
    }
    /** C type : char* */
    @Field(1) 
    public libvlc_track_description_t psz_name(Pointer<Byte > psz_name) {
        this.io.setPointerField(this, 1, psz_name);
        return this;
    }
    /** C type : libvlc_track_description_t* */
    @Field(2) 
    public Pointer<libvlc_track_description_t > p_next() {
        return this.io.getPointerField(this, 2);
    }
    /** C type : libvlc_track_description_t* */
    @Field(2) 
    public libvlc_track_description_t p_next(Pointer<libvlc_track_description_t > p_next) {
        this.io.setPointerField(this, 2, p_next);
        return this;
    }
    public libvlc_track_description_t() {
        super();
    }
    public libvlc_track_description_t(Pointer pointer) {
        super(pointer);
    }
}

