package com.tek.vlc.bridj;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libvlc") 
public class libvlc_rectangle_t extends StructObject {
    static {
        BridJ.register();
    }
    @Field(0) 
    public int top() {
        return this.io.getIntField(this, 0);
    }
    @Field(0) 
    public libvlc_rectangle_t top(int top) {
        this.io.setIntField(this, 0, top);
        return this;
    }
    @Field(1) 
    public int left() {
        return this.io.getIntField(this, 1);
    }
    @Field(1) 
    public libvlc_rectangle_t left(int left) {
        this.io.setIntField(this, 1, left);
        return this;
    }
    @Field(2) 
    public int bottom() {
        return this.io.getIntField(this, 2);
    }
    @Field(2) 
    public libvlc_rectangle_t bottom(int bottom) {
        this.io.setIntField(this, 2, bottom);
        return this;
    }
    @Field(3) 
    public int right() {
        return this.io.getIntField(this, 3);
    }
    @Field(3) 
    public libvlc_rectangle_t right(int right) {
        this.io.setIntField(this, 3, right);
        return this;
    }
    public libvlc_rectangle_t() {
        super();
    }
    public libvlc_rectangle_t(Pointer pointer) {
        super(pointer);
    }
}

