package com.tek.vlc.bridj;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libvlc") 
public class libvlc_subtitle_track_t extends StructObject {
    static {
        BridJ.register();
    }
    /** C type : char* */
    @Field(0) 
    public Pointer<Byte > psz_encoding() {
        return this.io.getPointerField(this, 0);
    }
    /** C type : char* */
    @Field(0) 
    public libvlc_subtitle_track_t psz_encoding(Pointer<Byte > psz_encoding) {
        this.io.setPointerField(this, 0, psz_encoding);
        return this;
    }
    public libvlc_subtitle_track_t() {
        super();
    }
    public libvlc_subtitle_track_t(Pointer pointer) {
        super(pointer);
    }
}

