package com.tek.vlc.bridj;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libvlc") 
public class libvlc_audio_output_device_t extends StructObject {
    static {
        BridJ.register();
    }
    /**
     * < Next entry in list<br>
     * C type : libvlc_audio_output_device_t*
     */
    @Field(0) 
    public Pointer<libvlc_audio_output_device_t > p_next() {
        return this.io.getPointerField(this, 0);
    }
    /**
     * < Next entry in list<br>
     * C type : libvlc_audio_output_device_t*
     */
    @Field(0) 
    public libvlc_audio_output_device_t p_next(Pointer<libvlc_audio_output_device_t > p_next) {
        this.io.setPointerField(this, 0, p_next);
        return this;
    }
    /**
     * < Device identifier string<br>
     * C type : char*
     */
    @Field(1) 
    public Pointer<Byte > psz_device() {
        return this.io.getPointerField(this, 1);
    }
    /**
     * < Device identifier string<br>
     * C type : char*
     */
    @Field(1) 
    public libvlc_audio_output_device_t psz_device(Pointer<Byte > psz_device) {
        this.io.setPointerField(this, 1, psz_device);
        return this;
    }
    /**
     * < User-friendly device description<br>
     * C type : char*
     */
    @Field(2) 
    public Pointer<Byte > psz_description() {
        return this.io.getPointerField(this, 2);
    }
    /**
     * < User-friendly device description<br>
     * C type : char*
     */
    @Field(2) 
    public libvlc_audio_output_device_t psz_description(Pointer<Byte > psz_description) {
        this.io.setPointerField(this, 2, psz_description);
        return this;
    }
    public libvlc_audio_output_device_t() {
        super();
    }
    public libvlc_audio_output_device_t(Pointer pointer) {
        super(pointer);
    }
}

